name: Recompile README.md
on:
  push:
    branches:
      - main
    paths:
      - "resources.csv"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository content
        uses: actions/checkout@v2

      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          
      - name: Install the required packages
        working-directory: ./compilation_script
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute the Python script
        working-directory: ./compilation_script
        run: python compile.py

      - name: Commit the changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Recompiles README.md" -a
          
      - name: Push the commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  